FR_System/FR_System/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using FR_System.Models;
using System.Linq;
using System;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

namespace FR_System.Controllers
{
    public class AdminController : Controller
    {
        public ContextDB context;

        public AdminController(ContextDB _context)
        {
            context = _context;
        }
        public IActionResult Index()
        {
            return RedirectToAction("Login");
        }
        public IActionResult Login()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return View();

            else
                return RedirectToAction("Dashboard");   
        }
        [HttpPost]
        public IActionResult Login(Admin ad)
        {
            var x = context.Admins.Where(a => a.AdminName == ad.AdminName && a.Password == ad.Password).FirstOrDefault();

            if (x != null)
            {
                HttpContext.Session.SetString("u", x.AdminName);
                HttpContext.Session.SetString("AID", x.AdminId.ToString());
                return RedirectToAction("Dashboard");
            }
            else
            {
                ViewBag.m = "Wrong User ID or Password";
            }
            return View();
        }

        public IActionResult Dashboard()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login");
            else
            {
                int id = int.Parse(HttpContext.Session.GetString("AID"));

                var admin = context.Admins.Find(id);
                if (admin == null)
                {
                    ViewBag.m = "ID or UserName not Matched";
                    return RedirectToAction("Login");
                }
                return View(admin);
            }

        }
        public IActionResult Users()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login");
            IEnumerable<User> userList = context.Users;
            return View(userList);
        }
        public IActionResult UserReservation(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login");
            List<Reservation> reserve = context.Reservations.ToList();
            var usertickets = from r in reserve
                              where r.UserId == id
                              select new TicketViewModel
                              {
                                  flights = context.Flights.Find(r.FlightId),
                                  reservations = r,
                                  userid = id,
                              };
            return View(usertickets);
        }
        public IActionResult Logout()
        {
            HttpContext.Session.SetString("u", String.Empty);
            HttpContext.Session.SetString("AID", String.Empty);
            return RedirectToAction("Login");
        }
    }
}

FR_System/FR_System/Controllers/FlightController.cs
using FR_System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace FR_System.Controllers
{
    public class FlightController : Controller
    {
        private readonly ContextDB _db;

        public FlightController(ContextDB db)
        {
            _db = db;
        }
        // GET-Create Action
        public IActionResult Create()
        {
            var planeids=new List<SelectListItem>();
            foreach(var p in _db.Planes)
                planeids.Add(new SelectListItem() { Value=p.PlaneID.ToString(), Text=p.PlaneID+"-"+p.PlaneName});
            ViewBag.PlaneID = planeids;
            return View();
        }

        // POST-Create Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Flight flight)
        {
            _db.Flights.Add(flight);
            _db.SaveChanges();
            return RedirectToAction("Details");
        }

        public IActionResult Details()
        {
            IEnumerable<Flight> flightList = _db.Flights;
            return View(flightList);
        }
        // GET - Delete Action
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var flight = _db.Flights.Find(id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        // POST-Delete Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(Flight? f)
        {
            if (f == null)
            {
                return NotFound();
            }
            int id = f.FlightId;
            var flight = _db.Flights.Find(id);
            if (flight == null)
            {
                return NotFound();
            }

            _db.Flights.Remove(flight);
            _db.SaveChanges();
            return RedirectToAction("Details");
        }

        // GET - Update Action
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var flight = _db.Flights.Find(id);
            if (flight == null)
            {
                return NotFound();
            }
            var planeids = new List<SelectListItem>();
            foreach (var p in _db.Planes)
                planeids.Add(new SelectListItem() { Value = p.PlaneID.ToString(), Text = p.PlaneID + "-" + p.PlaneName });
            ViewBag.PlaneID = planeids;
            return View(flight);
        }

        // POST-Delete Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdatePost(Flight? f)
        {
            if (f == null)
            {
                return NotFound();
            }
            _db.Flights.Update(f);
            _db.SaveChanges();
            return RedirectToAction("Details");
        }
    }
}

FR_System/FR_System/Controllers/PlaneController.cs
using FR_System.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace FR_System.Controllers
{
    public class PlaneController : Controller
    {
        private readonly ContextDB _db;

        public PlaneController(ContextDB db)
        {
            _db = db;
        }
        public IActionResult Create()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login", "Admin");
            return View();
        }

        // POST-Create Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Plane plane)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login", "Admin");
            _db.Planes.Add(plane);
            _db.SaveChanges();
            return RedirectToAction("Details");
        }
        public IActionResult Details()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login", "Admin");
            IEnumerable<Plane> planeList = _db.Planes;
            return View(planeList);
        }
        // GET - Delete Action
        public IActionResult Delete(int? id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login", "Admin");
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var plane = _db.Planes.Find(id);
            if (plane == null)
            {
                return NotFound();
            }
            return View(plane);
        }

        // POST - Delete Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int? id, Plane p)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login", "Admin");
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var plane = _db.Planes.Find(id);
            if (plane == null)
            {
                return NotFound();
            }

            _db.Planes.Remove(plane);
            _db.SaveChanges();
            return RedirectToAction("Details");
        }

        // GET - Update Action
        public IActionResult Update(int? id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login", "Admin");
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var plane = _db.Planes.Find(id);
            if (plane == null)
            {
                return NotFound();
            }
            return View(plane);
        }

        // POST-Update Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Plane p)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login", "Admin");
            if (p == null)
            {
                return NotFound();
            }
            _db.Planes.Update(p);
            _db.SaveChanges();
            return RedirectToAction("Details");
        }

    }
}

FR_System/FR_System/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using FR_System.Models;
using System.Linq;
using System;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

namespace FR_System.Controllers
{
    public class UserController : Controller
    {
        public ContextDB context;

        public UserController(ContextDB _context)
        {
            context = _context;
        }
        public IActionResult Index()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("username")))
                return View("Dashboard");
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Login()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("username")))
                return View();

            else
                return RedirectToAction("Dashboard");
        }
        [HttpPost]
        public IActionResult Login(User ad)
        {
            var x = context.Users.Where(a => a.UserName == ad.UserName && a.Password == ad.Password).FirstOrDefault();

            if (x != null)
            {
                HttpContext.Session.SetString("username", x.UserName);
                HttpContext.Session.SetString("userid", x.UserId.ToString());
                return RedirectToAction("Dashboard");
            }
            else
            {
                ViewBag.m = "Wrong User ID or Password";
            }
            return View();
        }

        public IActionResult Dashboard()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("username")))
                return RedirectToAction("Login");
            else
            {
                int id = int.Parse(HttpContext.Session.GetString("userid"));

                var user = context.Users.Find(id);
                if (user == null)
                {
                    ViewBag.m = "ID or UserName not Matched";
                    return RedirectToAction("Login");
                }
                return View(user);
            }
        }

        public IActionResult Register()
        {

            if (string.IsNullOrEmpty(HttpContext.Session.GetString("username")))
                return View();
            else
                return RedirectToAction("Dashboard");
        }

        [HttpPost]
        public IActionResult Register(User user)
        {
            ViewBag.regm = "hello";
            if (ModelState.IsValid)
            {
                if (user == null)
                {
                    return NoContent();
                }
                var x = context.Users.Where(a => a.Email == user.Email).FirstOrDefault();
                if (x != null)
                {
                    ViewBag.regm = "User with same Email ID is registered";
                    return View();
                }
                x = context.Users.Where(a => a.UserName == user.UserName).FirstOrDefault();
                if (x != null)
                {
                    ViewBag.regm = "User Name not available";
                    return View();
                }
                context.Users.Add(user);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        public IActionResult Logout()
        {
            HttpContext.Session.SetString("username", String.Empty);
            HttpContext.Session.SetString("userid", String.Empty);
            return RedirectToAction("Index","Home");
        }
    }
}

FR_System/FR_System/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<!-- Bootstrap Core CSS -->
<link href="~/web/css/bootstrap.css" rel='stylesheet' type='text/css' />

<!-- Custom CSS -->
<link href="~/web/css/style.css" rel='stylesheet' type='text/css' />

<!-- font-awesome icons CSS -->
<link href="~/web/css/font-awesome.css" rel="stylesheet"> 
<!-- //font-awesome icons CSS-->

<!-- side nav css file -->
<link href='~/web/css/SidebarNav.min.css' media='all' rel='stylesheet' type='text/css'/>
<!-- //side nav css file -->
 
 <!-- js-->
<script src="~/web/js/jquery-1.11.1.min.js"></script>
<script src="~/web/js/modernizr.custom.js"></script>

<!--webfonts-->
<link href="//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet">
<!--//webfonts--> 

<!-- Metis Menu -->
<script src="~/web/js/metisMenu.min.js"></script>
<script src="~/web/js/custom.js"></script>
<link href="~/web/css/custom.css" rel="stylesheet">
<!--//Metis Menu -->
	<!-- requried-jsfiles-for owl -->
					<link href="~/web/css/owl.carousel.css" rel="stylesheet">
					<script src="~/web/js/owl.carousel.js"></script>
						<script>
							$(document).ready(function() {
								$("#owl-demo").owlCarousel({
									items : 3,
									lazyLoad : true,
									autoPlay : true,
									pagination : true,
									nav:true,
								});
							});
						</script>
					<!-- //requried-jsfiles-for owl -->
</head>
<body class="cbp-spmenu-push">
	<div class="main-content">
	<div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
		<!--left-fixed -navigation-->
		<aside class="sidebar-left">
      <nav class="navbar navbar-inverse">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <h1><a class="navbar-brand"  asp-action="Dashboard" asp-controller="Admin"><span class="fa fa-plane"></span> Flight<span class="dashboard_text">Reservation</span></a></h1>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="sidebar-menu">
              <li class="treeview">
                <a asp-action="Dashboard" asp-controller="Admin">
                <i class="fa fa-dashboard"></i> <span>Admin Dashboard</span>
                </a>
              </li>
			  <li class="treeview">
                <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Plane</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a asp-controller="Plane" asp-action="Create"><i class="fa fa-angle-right"></i> Add</a></li>
                  <li><a asp-controller="Plane" asp-action="Details"><i class="fa fa-angle-right"></i> Details</a></li>
                </ul>
              </li>
              
              
              <li class="treeview">
                <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Flight</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a asp-controller="Flight" asp-action="Create"><i class="fa fa-angle-right"></i> Add</a></li>
                  <li><a asp-controller="Flight" asp-action="Details"><i class="fa fa-angle-right"></i> Details</a></li>
                </ul>
              </li>
			  <li>
                <a  asp-controller="Admin" asp-action="Users">
                <i class="fa fa-th"></i> <span>Users</span>
                </a>
              </li>
              
              
              
             
            </ul>
          </div>
          <div class="col" style="padding: 12px 5px 12px 15px;">
                    <a class="btn btn-danger w-75" asp-action="Logout" asp-controller="Admin">Logout</a>
          </div>
          <!-- /.navbar-collapse -->
      </nav>
    </aside>
	</div>
    <div class="sticky-header header-section ">
			
	<div class="clearfix"> </div>	
    </div>
    <div>
        @RenderBody()
    </div>
    <!--footer-->
	<div class="footer">
	   <p>&copy; 2022 Flight Reservation Dashboard. </p>		
	</div>
    <!--//footer-->
	</div>
		
	
	
	
	<!-- Classie --><!-- for toggle left push menu script -->
		<script src="~/web/js/classie.js"></script>
		<script>
			var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
				showLeftPush = document.getElementById( 'showLeftPush' ),
				body = document.body;
				
			showLeftPush.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( body, 'cbp-spmenu-push-toright' );
				classie.toggle( menuLeft, 'cbp-spmenu-open' );
				disableOther( 'showLeftPush' );
			};
			

			function disableOther( button ) {
				if( button !== 'showLeftPush' ) {
					classie.toggle( showLeftPush, 'disabled' );
				}
			}
		</script>
	<!-- //Classie --><!-- //for toggle left push menu script -->
		
	<!--scrolling js-->
	<script src="~/web/js/jquery.nicescroll.js"></script>
	<script src="~/web/js/scripts.js"></script>
	<!--//scrolling js-->
	
	<!-- side nav js -->
	<script src='~/web/js/SidebarNav.min.js' type='text/javascript'></script>
	<script>
      $('.sidebar-menu').SidebarNav()
    </script>
	<!-- //side nav js -->
	
	<!-- for index page weekly sales java script -->
	
	
	<!-- Bootstrap Core JavaScript -->
   <script src="~/web/js/bootstrap.js"> </script>
	<!-- //Bootstrap Core JavaScript -->

	
</body>
</html>

FR_System/FR_System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FR_System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container d-flex flex-row justify-content-between">
                <a class="navbar-brand mb-0 h1" style="font-size: large;" asp-area="" asp-controller="Home" asp-action="Index">Flight.com</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Search">Search Flight</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                <div class="flex-end">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item mr-3">
                            <a class="btn btn-outline-primary btn-lg w-10" role="button" style="padding: 0.2rem 1.2rem" asp-controller="User" asp-action="Login">Log in</a>
                        </li>
                        <li class="nav-item">
                             <a class="btn btn-primary btn-lg me-2 w-10" role="button" style="padding: 0.2rem 1.2rem" asp-controller="User" asp-action="Register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @RenderBody()


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FR_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FR_System/FR_System/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<!-- Bootstrap Core CSS -->
<link href="~/web/css/bootstrap.css" rel='stylesheet' type='text/css' />

<!-- Custom CSS -->
<link href="~/web/css/style.css" rel='stylesheet' type='text/css' />

<!-- font-awesome icons CSS -->
<link href="~/web/css/font-awesome.css" rel="stylesheet"> 
<!-- //font-awesome icons CSS-->

<!-- side nav css file -->
<link href='~/web/css/SidebarNav.min.css' media='all' rel='stylesheet' type='text/css'/>
<!-- //side nav css file -->
 
 <!-- js-->
<script src="~/web/js/jquery-1.11.1.min.js"></script>
<script src="~/web/js/modernizr.custom.js"></script>

<!--webfonts-->
<link href="//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet">
<!--//webfonts--> 

<!-- Metis Menu -->
<script src="~/web/js/metisMenu.min.js"></script>
<script src="~/web/js/custom.js"></script>
<link href="~/web/css/custom.css" rel="stylesheet">
<!--//Metis Menu -->
	<!-- requried-jsfiles-for owl -->
					<link href="~/web/css/owl.carousel.css" rel="stylesheet">
					<script src="~/web/js/owl.carousel.js"></script>
						<script>
							$(document).ready(function() {
								$("#owl-demo").owlCarousel({
									items : 3,
									lazyLoad : true,
									autoPlay : true,
									pagination : true,
									nav:true,
								});
							});
						</script>
					<!-- //requried-jsfiles-for owl -->
</head>
<body class="cbp-spmenu-push">
	<div class="main-content">
	<div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
		<!--left-fixed -navigation-->
		<aside class="sidebar-left">
      <nav class="navbar navbar-inverse">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <h1><a class="navbar-brand"  asp-action="Dashboard" asp-controller="User"><span class="fa fa-plane"></span> Flight<span class="dashboard_text">Reservation</span></a></h1>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="sidebar-menu">
              <li class="treeview">
                <a asp-action="Dashboard" asp-controller="User">
                <i class="fa fa-dashboard"></i> <span>User Dashboard</span>
                </a>
              </li>
			  <li class="treeview">
                <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Search Flight</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a asp-controller="Home" asp-action="Search"><i class="fa fa-angle-right"></i> Search</a></li>
                </ul>
              </li>
              
              
              <li class="treeview">
                <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Booking</span>
                <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                  <li><a asp-controller="Home" asp-action="Search"><i class="fa fa-angle-right"></i> Create Booking</a></li>
				  <li><a asp-controller="Reservation" asp-action="BookingDetails"><i class="fa fa-angle-right"></i> Booking Status</a></li>
                </ul>
              </li> 
            </ul>
          </div>
          <div class="col" style="padding: 12px 5px 12px 15px;">
                    <a class="btn btn-danger w-75" asp-action="Logout" asp-controller="User">Logout</a>
          </div>
          <!-- /.navbar-collapse -->
      </nav>
    </aside>
	</div>
    <div class="sticky-header header-section ">
			
	<div class="clearfix"> </div>	
    </div>
    <div>
        @RenderBody()
    </div>
    <!--footer-->
	<div class="footer">
	   <p>&copy; 2022 Flight Reservation Dashboard. </p>		
	</div>
    <!--//footer-->
	</div>
		
	
	
	
	<!-- Classie --><!-- for toggle left push menu script -->
		<script src="~/web/js/classie.js"></script>
		<script>
			var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
				showLeftPush = document.getElementById( 'showLeftPush' ),
				body = document.body;
				
			showLeftPush.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( body, 'cbp-spmenu-push-toright' );
				classie.toggle( menuLeft, 'cbp-spmenu-open' );
				disableOther( 'showLeftPush' );
			};
			

			function disableOther( button ) {
				if( button !== 'showLeftPush' ) {
					classie.toggle( showLeftPush, 'disabled' );
				}
			}
		</script>
	<!-- //Classie --><!-- //for toggle left push menu script -->
		
	<!--scrolling js-->
	<script src="~/web/js/jquery.nicescroll.js"></script>
	<script src="~/web/js/scripts.js"></script>
	<!--//scrolling js-->
	
	<!-- side nav js -->
	<script src='~/web/js/SidebarNav.min.js' type='text/javascript'></script>
	<script>
      $('.sidebar-menu').SidebarNav()
    </script>
	<!-- //side nav js -->
	
	<!-- for index page weekly sales java script -->
	
	
	<!-- Bootstrap Core JavaScript -->
   <script src="~/web/js/bootstrap.js"> </script>
	<!-- //Bootstrap Core JavaScript -->

	
</body>
</html>