FR_System/FR_System/Models/Flight.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace FR_System.Models
{
    [Table("TblFlight")]
    public class Flight
    {
        [Key]
        public int FlightId { get; set; }

        [Required(ErrorMessage ="City Name Required")]
        [Display(Name = "From City")]
        public string FlightFrom { get; set; }

        [Required(ErrorMessage = "City Name Required")]
        [Display(Name = "To City")]
        public string FlightTo { get; set; }

        [Required(ErrorMessage = "Departure Date Required")]
        [Display(Name = "Departure Date")]
        [DataType(DataType.Date)]

        public System.DateTime FlightDDate { get; set; }

        [Required(ErrorMessage = "Departure Time Required")]
        [Display(Name = "Departure Time")]
        [StringLength(15)]
        public string DTime { get; set; }

        [Required(ErrorMessage = "Plane No Required"), Display(Name = "Plane No:")]
        public int PlaneID { get; set; }
        [ForeignKey("PlaneID")]
        public virtual Plane Planes { get; set; }

        [Required(ErrorMessage = "Price Required")]
        [Display(Name = "Price")]
        public decimal Price { get; set; }

        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}

FR_System/FR_System/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using FR_System.Models;
using System.Linq;
using System;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

namespace FR_System.Controllers
{
    public class AdminController : Controller
    {
        public ContextDB context;

        public AdminController(ContextDB _context)
        {
            context = _context;
        }
        public IActionResult Index()
        {
            return RedirectToAction("Login");
        }
        public IActionResult Login()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return View();

            else
                return RedirectToAction("Dashboard");   
        }
        [HttpPost]
        public IActionResult Login(Admin ad)
        {
            var x = context.Admins.Where(a => a.AdminName == ad.AdminName && a.Password == ad.Password).FirstOrDefault();

            if (x != null)
            {
                HttpContext.Session.SetString("u", x.AdminName);
                HttpContext.Session.SetString("AID", x.AdminId.ToString());
                return RedirectToAction("Dashboard");
            }
            else
            {
                ViewBag.m = "Wrong User ID or Password";
            }
            return View();
        }

        public IActionResult Dashboard()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login");
            else
            {
                int id = int.Parse(HttpContext.Session.GetString("AID"));

                var admin = context.Admins.Find(id);
                if (admin == null)
                {
                    ViewBag.m = "ID or UserName not Matched";
                    return RedirectToAction("Login");
                }
                return View(admin);
            }

        }
        public IActionResult Users()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login");
            IEnumerable<User> userList = context.Users;
            return View(userList);
        }
        public IActionResult UserReservation(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("u")))
                return RedirectToAction("Login");
            List<Reservation> reserve = context.Reservations.ToList();
            var usertickets = from r in reserve
                              where r.UserId == id
                              select new TicketViewModel
                              {
                                  flights = context.Flights.Find(r.FlightId),
                                  reservations = r,
                                  userid = id,
                              };
            return View(usertickets);
        }
        public IActionResult Logout()
        {
            HttpContext.Session.SetString("u", String.Empty);
            HttpContext.Session.SetString("AID", String.Empty);
            return RedirectToAction("Login");
        }
    }
}

FR_System/FR_System/Controllers/FlightController.cs
using FR_System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace FR_System.Controllers
{
    public class FlightController : Controller
    {
        private readonly ContextDB _db;

        public FlightController(ContextDB db)
        {
            _db = db;
        }
        // GET-Create Action
        public IActionResult Create()
        {
            var planeids=new List<SelectListItem>();
            foreach(var p in _db.Planes)
                planeids.Add(new SelectListItem() { Value=p.PlaneID.ToString(), Text=p.PlaneID+"-"+p.PlaneName});
            ViewBag.PlaneID = planeids;
            return View();
        }

        // POST-Create Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Flight flight)
        {
            _db.Flights.Add(flight);
            _db.SaveChanges();
            return RedirectToAction("Details");
        }

        public IActionResult Details()
        {
            IEnumerable<Flight> flightList = _db.Flights;
            return View(flightList);
        }
        // GET - Delete Action
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var flight = _db.Flights.Find(id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        // POST-Delete Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(Flight? f)
        {
            if (f == null)
            {
                return NotFound();
            }
            int id = f.FlightId;
            var flight = _db.Flights.Find(id);
            if (flight == null)
            {
                return NotFound();
            }

            _db.Flights.Remove(flight);
            _db.SaveChanges();
            return RedirectToAction("Details");
        }

        // GET - Update Action
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var flight = _db.Flights.Find(id);
            if (flight == null)
            {
                return NotFound();
            }
            var planeids = new List<SelectListItem>();
            foreach (var p in _db.Planes)
                planeids.Add(new SelectListItem() { Value = p.PlaneID.ToString(), Text = p.PlaneID + "-" + p.PlaneName });
            ViewBag.PlaneID = planeids;
            return View(flight);
        }

        // POST-Delete Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdatePost(Flight? f)
        {
            if (f == null)
            {
                return NotFound();
            }
            _db.Flights.Update(f);
            _db.SaveChanges();
            return RedirectToAction("Details");
        }
    }
}

FR_System/FR_System/Views/Flight/Create.cshtml
@model FR_System.Models.Flight

@{
    ViewData["Title"] = "Create Flight";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    
}

<div id="page-wrapper">
			<div class="main-page">
				<h2 class="title1">Add Flight Details</h2>
				<div class="blank-page widget-shadow scroll" id="style-2 div1">
<form method="post" asp-action="Create">
        @* <div class="form-group row">
           <h2 class="text-black-50 pl-3">Add Flight Details</h2>
        </div> *@
        <div class="form-group row">
            <label asp-for="FlightFrom" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input type="text" class="form-control" asp-for="FlightFrom" placeholder="Type City...">
                <span asp-validation-for="FlightFrom" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="FlightTo" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input type="text" class="form-control" asp-for="FlightTo" placeholder="Type City...">
                <span asp-validation-for="FlightTo" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="FlightDDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="FlightDDate" placeholder="Select date" type="date" class="form-control">
                @*<i class="fas fa-calendar input-prefix" tabindex=0></i>*@
                <span asp-validation-for="FlightDDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="DTime" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="DTime" placeholder="Select date" type="time" class="form-control">
                @*<i class="fas fa-clock-o input-prefix" tabindex=0></i>*@
                <span asp-validation-for="DTime" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="PlaneID" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                @*<input type="text" class="form-control" asp-for="PlaneID" placeholder="Plane ID">*@
                <select asp-for="PlaneID" class ="form-control" asp-items="ViewBag.PlaneID"></select>
                @*<span asp-validation-for="PlaneID" class="text-danger"></span>*@
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input type="text" class="form-control" asp-for="Price" placeholder="Price">
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-8 offset-2 row">
                <div class="col">
                    <input type="submit" class="btn btn-info w-75" value="Add Flight" />
                </div>
                <div class="col">
                      <a class="btn btn-danger w-75" asp-action="Details" asp-controller="Flight">Back</a>
                </div>
            </div>
         </div>
</form>
</div>
</div>
</div>
<script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

FR_System/FR_System/Views/Flight/Delete.cshtml
@model FR_System.Models.Flight

@{
    ViewData["Title"] = "Delete Flight";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    
}

<div id="page-wrapper">
			<div class="main-page">
				<h2 class="title1">Delete Flight</h2>
				<div class="blank-page widget-shadow scroll" id="style-2 div1">
<form method="post" asp-action="DeletePost">
        <div class="border p-3">
            @* <div class="form-group row">
                <h2 class="text-black-50 pl-3">Delete Flight Details</h2>
            </div> *@
            <div class="row">
                <div class="col-12">
                    <div hidden class="form-group row">
                        <label asp-for="FlightId" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" asp-for="FlightId">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="FlightFrom" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input type="text" disabled class="form-control" asp-for="FlightFrom">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="FlightTo" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input type="text" disabled class="form-control" asp-for="FlightTo">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="FlightDDate" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="FlightDDate" disabled type="date" class="form-control">
                            
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="DTime" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="DTime" disabled placeholder="Select date" type="time" class="form-control">
                            
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="PlaneID" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input type="text" disabled class="form-control" asp-for="PlaneID" placeholder="Plane ID">
                        </div>
                    </div>
                  <div class="form-group row">
                        <label asp-for="Price" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input type="text" disabled class="form-control" asp-for="Price" placeholder="Price">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-8 offset-2 row">
                            <div class="col">
                                <input type="submit" class="btn btn-danger w-75" value="Delete Flight" />
                            </div>
                            <div class="col">
                                <a class="btn btn-success w-75" asp-action="Details" asp-controller="Flight">Back</a>
                            </div>
                        </div>
                     </div>
                </div>
            </div>
        </div>
        
        
</form>
</div>
</div>
</div>

FR_System/FR_System/Views/Flight/Details.cshtml
@model IEnumerable<FR_System.Models.Flight>

@{
    ViewData["Title"] = "Flight Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    
}

<div id="page-wrapper">
			<div class="main-page">
				<h2 class="title1">Index-Flight Details</h2>
				<div class="blank-page widget-shadow scroll" id="style-2 div1">
@* <h1>Index-Flight Details</h1> *@
<div class="container p-3">
	<div class="row pt-4">
		<div class="col-6">
			<h2 class="text-primary">Flight Details List</h2>
		</div>
	</div>
	<br />

	@if(Model.Count() > 0)
	{
		<table class="table table-bordered table-striped" style="width:90%">
			<thead>
				<tr>
					<th>Flight Id</th>
					<th>From City</th>
					<th>To City</th>
					<th>Departure Date</th>
					<th>Departure Time</th>
					<th>Plane ID</th>
					<th>Price</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
			   {
				   <tr>
					   <td width="10%">@item.FlightId</td>
					   <td width="10%">@item.FlightFrom</td>
					   <td width="10%">@item.FlightTo</td>
					   <td width="10%">@item.FlightDDate</td>
					   <td width="10%">@item.DTime</td>
					   <td width="10%">@item.PlaneID</td>
					   <td width="10%">@item.Price</td>
					   <td width="20%">
						   <div class="w-100 btn-group" role="group">
								<a asp-controller="Flight" asp-action="Update" asp-route-Id="@item.FlightId" class="btn btn-primary mx-1">Update Flight</a>
								<a asp-controller="Flight" asp-action="Delete" asp-route-Id="@item.FlightId" style="margin-top: 10px;" class="btn btn-danger mx-1">Delete Flight</a>
						   </div>
					   </td>
				   </tr>
			   }
			</tbody>
		</table>
	}
	else
	{
		<p>No flight details available.</p>

	}
		  <a class="btn btn-danger w-20" asp-action="Dashboard" asp-controller="Admin">Back</a>
</div>
</div>
</div>
</div>

FR_System/FR_System/Views/Flight/Update.cshtml
@model FR_System.Models.Flight

@{
    ViewData["Title"] = "Update Flight";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    
}

<div id="page-wrapper">
			<div class="main-page">
				<h2 class="title1">Update Flight Details</h2>
				<div class="blank-page widget-shadow scroll" id="style-2 div1">
<form method="post" asp-action="UpdatePost">
        <div class="border p-3">
            @* <div class="form-group row">
                <h2 class="text-black-50 pl-3">Update Flight Details</h2>
            </div> *@
            <div class="row">
                <div class="col-12">
                    <div hidden class="form-group row">
                        <label asp-for="FlightId" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" asp-for="FlightId">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="FlightFrom" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" asp-for="FlightFrom">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="FlightTo" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" asp-for="FlightTo">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="FlightDDate" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="FlightDDate" type="date" class="form-control">
                            @*<i class="fas fa-calendar input-prefix" tabindex=0></i>*@
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="DTime" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="DTime" placeholder="Select date" type="time" class="form-control">
                            
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="PlaneID" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <select asp-for="PlaneID" class ="form-control" asp-items="ViewBag.PlaneID"></select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Price" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" asp-for="Price " placeholder="Price">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-8 offset-2 row">
                            <div class="col">
                                <input type="submit" class="btn btn-success w-75" value="Update Flight" />
                            </div>
                            <div class="col">
                                     <a class="btn btn-danger w-75" asp-action="Details" asp-controller="Flight">Back</a>
                            </div>
                        </div>
                     </div>
                </div>
            </div>
        </div>
        
        
</form>

</div>
			</div>
		</div>
<script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>